### ISSUE TITLE
.pnp-internal not shown

### ISSUE THREAD

**Issue by wolf-in-sheeps-clothing** [lingej/pnp-metrics-api#6]
The current Version didn't show the .pnp-internal in Grafana. I've got an earlier version of the api.php on an other server. I copied this version to my test server and the .pnp-internal output is ok.

Is it intended that the internal statistics can no longer be queried or is there an error in the current version?

Thanks.

**Comment by sni** [comment]
This is not intented and should "just" work. The pnp-internals are not listed in the drop down, but the example dashboard uses them and they should provide valid data if they exist on the server.

**Comment by wolf-in-sheeps-clothing** [comment]
Thanks for your fast reply.
I've testet this a few times but the .pnp-internal didn't work.

On my testserver I setup a fresh installation, used the latest api.php and the latetst grafana data source via "grafana-cli plugins install sni-pnp-datasource" with the dashboards.

I can see an output from the testserver data (disk, ssh, load and so on) but no .pnp-internals. If I changed to the "old" api.php the output of .pnp-internals work fine. Change back, output of the testserver is fine, but no .pnp-internal. Change again -> fine! So it must be something wrong in the api.php.

In PNP Web I see .pnp-internal data, so they exists.

xxx@testserver:/usr/local/pnp4nagios/var/perfdata/.pnp-internal$ ls
runtime_create.rrd  runtime_errors.rrd  runtime_invalid.rrd  runtime_rows.rrd  runtime_runtime.rrd  runtime_skipped.rrd  runtime_update.rrd  runtime.xml

By the way: latest version grafana from grafana repository. Installed via apt.
Testserver and Prod-Server is an identical installation (exept the api.php). I use the testserver to test any update bevor installation on Prod.

**Comment by sni** [comment]
Could you try this patch?
-> https://github.com/sni/pnp-metrics-api/commit/a92def83e447f14b38e2ff0c12058d39eaf9e92a

**Comment by wolf-in-sheeps-clothing** [comment]
Hey,
sorry, but it didn't work. Farther "no data points" in Grafana.
Back to the "old" Version -> immediately I see a graph.

**Comment by sni** [comment]
ok, this time for real: https://github.com/sni/pnp-metrics-api/commit/11c20c877772e7eedcec720ff21447a843ee9ca3
You can simply fetch the latest api.php from here:
https://raw.githubusercontent.com/sni/pnp-metrics-api/master/application/controller/api.php

**Comment by wolf-in-sheeps-clothing** [comment]
Yeah, that's awesome! Looks great again. Thanks.
So in my opinion the last code could merged. "Bug" is gone.

**Comment by sni** [comment]
done in #7
